version: '3.8'

services:
  web:
    build:
      context: .
    restart: always
    command: >
      sh -c "python manage.py migrate && 
            gunicorn gems_customers.wsgi:application --bind 0:8000"
    env_file:
      - ./.env
    ports:
      - "8000:8000"
